cheezlbot:
  guild-id: "1044843245408112672"
  allowed-text-channels: "1058889405928046642"
  wireguard:
    uri: "http://10.0.0.23:51821"
  api-url: "http://127.0.0.1:8081"
spring:
  security:
    oauth2:
      client:
        registration:
          cheezlbot:
            client-id: cheezlbot-dev