cheezlbot:
  guild-id: "458721282620522499"
  allowed-text-channels: "938190971772993617"
  api-uri: "http://127.0.0.1:8081"
  randomizer-bounds: 3

wireguard:
  uri: "http://localhost:51821"
  password: "PokettoMonster0912!"
logging:
  level:
    root: info
